
-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD HH:MM:SS.MMM)
SELECT GETDATE() data_com_hora

-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD)
SELECT CAST(GETDATE() AS DATE) data_sem_hora

-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD), ANO, MES e DIA
SELECT CAST(GETDATE() AS DATE) data_sem_hora
,year(GETDATE()) ANO
,month(GETDATE()) MES
,day(GETDATE()) DIA


-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD), HORA (FORMADO HH:MM:SS), HORA, MINUTO e SEGUNDO
SELECT GETDATE() data_com_hora
,FORMAT(CAST(GETDATE() AS DATETIME), 'hh:mm:ss') hora_completa
,DATEPART(HOUR,  GETDATE()) HORA
,DATEPART(MINUTE,  GETDATE()) MINUTO
,DATEPART(SECOND,  GETDATE()) SEGUNDO

SET LANGUAGE 'ENGLISH'

-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD HH:MM:SS.MMM), DIA DA SEMANA, NOME DO MÊS, DIA DO ANO, SEMANA DO ANO
SELECT GETDATE() data_com_hora
,DATENAME(dw,GETDATE()) dia_semana
,DATEPART(dw,GETDATE()) dia_semana_numerico
,DATENAME(month, GETDATE()) mes_descricao
,DATEPART(DAYOFYEAR, GETDATE()) dia_do_ano
,DATEPART(WEEK,GETDATE()) semana_do_ano

SET LANGUAGE 'PORTUGUESE'

-- SELECIONAR A DATA DE AGORA (FORMATO YYYY-MM-DD HH:MM:SS.MMM), DIA DA SEMANA, NOME DO MÊS, DIA DO ANO, SEMANA DO ANO
SELECT GETDATE() data_com_hora
,DATENAME(dw,GETDATE()) dia_semana
,DATEPART(dw,GETDATE()) dia_semana_numerico
,DATENAME(month, GETDATE()) mes_descricao
,DATEPART(DAYOFYEAR, GETDATE()) dia_do_ano
,DATEPART(WEEK,GETDATE()) semana_do_ano